### PR TITLE
refactor: inclusion in prototype services readme

### PR DESCRIPTION
**Pull request by Dudleyneedham**
## fixes https://github.com/KILTprotocol/ticket/issues/607

Had a question inside the RIOT channel regarding the local setup. 

Noticed there was no mention of the Prototype serivces.

## How to test:

Let us think of stuff.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

### CODE REVIEW

**Comment by flechtnergalani** [comment]
I wasn't aware the readme was so outdated. No mention of the docker-compose instructions ([see our internal documentation](https://github.com/KILTprotocol/organizational/wiki/running-KILT-components-with-docker-&-docker-compose)). [This](https://github.com/KILTprotocol/organizational/wiki/Setting-up-&-running-KILT-components) could also help in improving the readme.

**Comment by Dudleyneedham** [comment]
If you want to add somethings please do.

**Comment by flechtnergalani** [comment]
> As discussed, we should change the default spin up to include the services in the future. But for now, this is fine.

services are already included, just use `docker-compose up`

**Comment by wischli** [comment]
> If you want to add somethings please do.

I will take care of this if @flechtnergalani does not jump in.

**Pull request merged**
